'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useAuth } from '../../../../lib/auth';
import { api } from '../../../../lib/api';
import { PageHeader } from '../../../../components/page-header';
import { StatusBadge } from '../../../../components/badge';
import { Table, Th, Td } from '../../../../components/table';
import { ErrorNotice, EmptyNotice } from '../../../../components/notice';
import { AttachmentPanel } from '../../../../components/attachment-panel';
import { ArrowUpRightIcon, CheckIcon, ClockIcon, XIcon } from '../../../../components/icons';
import { formatCurrency, formatDate, formatDateTime } from '../../../../lib/format';

export default function RequestDetailPage(){
  const params=useParams<{id:string}>(); const {user}=useAuth(); const qc=useQueryClient(); const q=useQuery({queryKey:['request',params.id],queryFn:()=>api.request(params.id)}); const [comment,setComment]=useState('');
  const submit=useMutation({mutationFn:()=>api.submitRequest(params.id),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['request',params.id]});await qc.invalidateQueries({queryKey:['requests']});await qc.invalidateQueries({queryKey:['dashboard']})}});
  const decide=useMutation({mutationFn:(decision:'APPROVED'|'REJECTED')=>api.decideRequest(params.id,{decision,comment:comment||undefined}),onSuccess:async()=>{setComment('');await qc.invalidateQueries({queryKey:['request',params.id]});await qc.invalidateQueries({queryKey:['requests']});await qc.invalidateQueries({queryKey:['dashboard']})}});
  const cancel=useMutation({mutationFn:()=>api.cancelRequest(params.id),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['request',params.id]});await qc.invalidateQueries({queryKey:['requests']})}});
  if(q.isLoading) return <div className="pf-loading-screen"><div className="pf-spinner"/>Loading request</div>; if(q.error) return <ErrorNotice message={q.error.message}/>;
  const r=q.data; const value=r.items.reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.estimatedUnitPriceCents),0);
  const canSubmit=r.status==='DRAFT'&&r.requesterId===user?.id; const canCancel=['DRAFT','SUBMITTED','PENDING_APPROVAL'].includes(r.status)&&r.requesterId===user?.id; const canDecide=r.status==='PENDING_APPROVAL'&&(user?.role==='MANAGER'||user?.role==='ADMIN')&&r.requesterId!==user?.id; const canOpenSourcing=user?.role==='PROCUREMENT'||user?.role==='ADMIN';
  return <div className="max-w-[1200px]"><PageHeader eyebrow={`Purchase requests / ${r.department?.name ?? 'Request'}`} title={r.title} description={r.justification} action={<Link href="/requests" className="pf-btn">Back to requests</Link>} meta={<StatusBadge value={r.status}/>}/><div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
    <div className="space-y-5"><section className="pf-panel overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-100 p-5"><div><div className="pf-card-title">Requested items</div><div className="pf-card-subtitle">Commercial baseline captured when the request was created.</div></div><div className="text-right"><div className="pf-label">Estimated total</div><div className="mt-1 text-[20px] font-[760]">{formatCurrency(value)}</div></div></div><Table><thead><tr><Th>Description</Th><Th>Qty</Th><Th>Unit</Th><Th>Unit price</Th><Th>Total</Th></tr></thead><tbody>{r.items.map((i:any)=><tr key={i.id}><Td><div className="font-semibold text-slate-800">{i.description}</div>{i.notes?<div className="mt-1 text-[10px] text-slate-400">{i.notes}</div>:null}</Td><Td>{Number(i.quantity)}</Td><Td>{i.unit}</Td><Td>{formatCurrency(i.estimatedUnitPriceCents)}</Td><Td className="font-semibold">{formatCurrency(Number(i.quantity)*Number(i.estimatedUnitPriceCents))}</Td></tr>)}</tbody></Table></section>
      <section className="pf-panel p-5"><div className="pf-section-head"><div><div className="pf-card-title">Approval history</div><div className="pf-card-subtitle">Decisions are immutable business events attached to this request.</div></div></div><div className="mt-4">{r.approvals?.length?r.approvals.map((a:any)=><div key={a.id} className="pf-timeline-item"><span className="pf-timeline-icon">{a.decision==='APPROVED'?<CheckIcon size={13}/>:<XIcon size={13}/>}</span><div className="min-w-0"><div className="text-[11px] font-bold">{a.approver?.name ?? 'Approver'} <span className="font-normal text-slate-400">· {a.decision}</span></div><div className="mt-1 text-[10px] text-slate-500">{a.comment||'No comment provided.'}</div><div className="mt-1 text-[9px] text-slate-400">{formatDateTime(a.decidedAt)}</div></div></div>):<div className="pf-timeline-item"><span className="pf-timeline-icon"><ClockIcon size={13}/></span><div><div className="text-[11px] font-bold">Awaiting decision</div><div className="mt-1 text-[10px] text-slate-500">No approval action has been recorded yet.</div></div></div>}</div></section>
      {r.rfqs?.length?<section className="pf-panel p-5"><div className="pf-card-title">Sourcing linkage</div><div className="pf-card-subtitle">Approved requests can be converted into RFQs by procurement.</div><div className="mt-4 space-y-2">{r.rfqs.map((rfq:any)=>{const row=<><span className="pf-kpi-icon">{canOpenSourcing?<ArrowUpRightIcon size={14}/>:<span className="text-[9px] font-bold">RFQ</span>}</span><span className="min-w-0"><strong className="block text-[11px]">{rfq.number}</strong><small className="block mt-1 text-[9px] text-slate-400">{rfq.title}</small></span><StatusBadge value={rfq.status}/></>; return canOpenSourcing?<Link key={rfq.id} href="/rfqs" className="flex items-center gap-3 rounded-[10px] border border-slate-200 p-3 hover:bg-slate-50">{row}</Link>:<div key={rfq.id} className="flex items-center gap-3 rounded-[10px] border border-slate-200 p-3">{row}</div>})}</div></section>:null}</div>
    <aside className="space-y-5"><section className="pf-panel p-5"><div className="pf-card-title">Request details</div><div className="mt-5 grid gap-4"><div><div className="pf-label">Requester</div><div className="mt-1 text-[11px] font-semibold">{r.requester?.name}</div><div className="text-[10px] text-slate-500">{r.requester?.email}</div></div><div><div className="pf-label">Department</div><div className="mt-1 text-[11px] font-semibold">{r.department?.name}</div></div><div><div className="pf-label">Budget</div><div className="mt-1 text-[11px] font-semibold">{r.budget?.name??'Not assigned'}</div></div><div><div className="pf-label">Needed by</div><div className="mt-1 text-[11px] font-semibold">{formatDate(r.neededBy)}</div></div><div><div className="pf-label">Created</div><div className="mt-1 text-[11px] font-semibold">{formatDateTime(r.createdAt)}</div></div></div></section>
      {canDecide?<section className="pf-panel p-5"><div className="pf-card-title">Manager decision</div><div className="pf-card-subtitle">Approval is a control point. Rejecting requires a recorded reason.</div><textarea className="pf-input mt-4 min-h-[105px] resize-y" placeholder="Decision comment" value={comment} onChange={e=>setComment(e.target.value)}/><div className="mt-3 grid grid-cols-2 gap-2"><button className="pf-btn" disabled={decide.isPending||!comment.trim()} onClick={()=>decide.mutate('REJECTED')}><XIcon size={14}/>Reject</button><button className="pf-btn pf-btn-primary" disabled={decide.isPending} onClick={()=>decide.mutate('APPROVED')}><CheckIcon size={14}/>Approve</button></div></section>:null}
      <section className="pf-panel p-5"><div className="pf-card-title">Actions</div><div className="mt-4 space-y-2">{canSubmit?<button className="pf-btn pf-btn-primary w-full" disabled={submit.isPending} onClick={()=>submit.mutate()}>{submit.isPending?'Submitting…':<>Submit for approval <ArrowUpRightIcon size={14}/></>}</button>:null}{canCancel?<button className="pf-btn pf-btn-danger w-full" disabled={cancel.isPending} onClick={()=>{if(window.confirm('Cancel this purchase request? This action cannot be undone after the workflow advances.')) cancel.mutate();}}>{cancel.isPending?'Cancelling…':<>Cancel request <XIcon size={14}/></>}</button>:null}{!canSubmit&&!canCancel&&!canDecide?<div className="text-[10px] leading-5 text-slate-500">No action is available at this workflow stage.</div>:null}</div>{(submit.error||decide.error||cancel.error)?<div className="mt-3"><ErrorNotice message={(submit.error||decide.error||cancel.error)!.message}/></div>:null}</section>
      <AttachmentPanel entityType="PurchaseRequest" entityId={r.id} canUpload={user?.role === 'EMPLOYEE' || user?.role === 'MANAGER' || user?.role === 'PROCUREMENT' || user?.role === 'ADMIN'}/></aside>
    </div></div>;
}
