'use client';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { api } from '../../../lib/api';
import { PageHeader } from '../../../components/page-header';
import { StatusBadge } from '../../../components/badge';
import { Table, Th, Td } from '../../../components/table';
import { EmptyNotice, ErrorNotice } from '../../../components/notice';
import { ArrowUpRightIcon, BuildingIcon, CheckIcon, RepeatIcon, PlusIcon } from '../../../components/icons';
import { formatCurrency, formatDate } from '../../../lib/format';

export default function RfqsPage() {
  const qc=useQueryClient();
  const rfqs=useQuery({queryKey:['rfqs'],queryFn:api.rfqs});
  const requests=useQuery({queryKey:['requests','approved'],queryFn:()=>api.requests('APPROVED')});
  const vendors=useQuery({queryKey:['vendors'],queryFn:()=>api.vendors()});
  const [requestId,setRequestId]=useState(''); const [inviteRfqId,setInviteRfqId]=useState(''); const [selectedVendorIds,setSelectedVendorIds]=useState<string[]>([]);
  const [rfqId,setRfqId]=useState(''); const [vendorId,setVendorId]=useState(''); const [quoteItems,setQuoteItems]=useState<any[]>([]); const [prices,setPrices]=useState<Record<string,string>>({}); const [leadTime,setLeadTime]=useState('7'); const [payment,setPayment]=useState('Net 30'); const [referenceNumber,setReferenceNumber]=useState(''); const [validUntil,setValidUntil]=useState('');
  const rows=rfqs.data??[];
  const createRfq=useMutation({mutationFn:()=>api.createRfq({purchaseRequestId:requestId}),onSuccess:async d=>{setRequestId('');setInviteRfqId(d.id);await qc.invalidateQueries({queryKey:['rfqs']});await qc.invalidateQueries({queryKey:['requests','approved']})}});
  const invite=useMutation({mutationFn:()=>api.inviteVendors(inviteRfqId,selectedVendorIds),onSuccess:async()=>{setSelectedVendorIds([]);await qc.invalidateQueries({queryKey:['rfqs']})}});
  const openRfq=rows.find((r:any)=>r.id===rfqId);
  const invited=openRfq?.invitations?.filter((i:any)=>i.status==='INVITED')??[];
  const createQuote=useMutation({mutationFn:()=>api.createQuote(rfqId,{vendorId,referenceNumber:referenceNumber.trim()||undefined,leadTimeDays:Number(leadTime),paymentTerms:payment.trim()||undefined,validUntil:validUntil||undefined,items:quoteItems.map(i=>({rfqItemId:i.id,quantity:Number(i.quantity),unitPrice:Number(prices[i.id]??0)}))}),onSuccess:async()=>{setVendorId('');setRfqId('');setQuoteItems([]);setPrices({});setReferenceNumber('');setValidUntil('');await qc.invalidateQueries({queryKey:['rfqs']})}});
  const select=useMutation({mutationFn:({rfqId,quoteId}:{rfqId:string;quoteId:string})=>api.selectQuote(rfqId,quoteId,{rationale:'Commercial comparison completed in procurement workspace.'}),onSuccess:()=>qc.invalidateQueries({queryKey:['rfqs']})});
  const toggleVendor=(id:string)=>setSelectedVendorIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
  const openOptions=useMemo(()=>rows.filter((r:any)=>r.status==='OPEN'),[rows]);
  if(rfqs.isLoading) return <div className="pf-loading-screen"><div className="pf-spinner"/>Loading sourcing</div>;
  return <div className="max-w-[1300px]"><PageHeader eyebrow="Source & buy / Sourcing" title="RFQs & quote comparison" description="Turn approved demand into a controlled supplier event, invite suppliers, record comparable quotations, and close the event only after a documented commercial selection." />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="pf-panel p-4"><div className="pf-label">Open RFQs</div><div className="mt-2 text-[22px] font-[760]">{openOptions.length}</div><div className="mt-1 text-[9.5px] text-slate-400">Active sourcing events</div></div><div className="pf-panel p-4"><div className="pf-label">Quotes received</div><div className="mt-2 text-[22px] font-[760]">{rows.reduce((s:number,r:any)=>s+r.quotes.length,0)}</div><div className="mt-1 text-[9.5px] text-slate-400">Across current RFQs</div></div><div className="pf-panel p-4"><div className="pf-label">Awards</div><div className="mt-2 text-[22px] font-[760]">{rows.reduce((s:number,r:any)=>s+r.quotes.filter((q:any)=>q.status==='SELECTED').length,0)}</div><div className="mt-1 text-[9.5px] text-slate-400">Selected quotes</div></div></div>
    <div className="grid gap-5 xl:grid-cols-3">
      <section className="pf-panel p-5"><div className="pf-section-head"><div><div className="pf-card-title">1. Create RFQ</div><div className="pf-card-subtitle">Only approved purchase requests are eligible.</div></div><span className="pf-step-dot"><PlusIcon size={13}/></span></div><select className="pf-input mt-5" value={requestId} onChange={e=>setRequestId(e.target.value)}><option value="">Approved request</option>{requests.data?.map((r:any)=><option key={r.id} value={r.id}>{r.title}</option>)}</select><button disabled={!requestId||createRfq.isPending} className="pf-btn pf-btn-primary mt-3 w-full" onClick={()=>createRfq.mutate()}>{createRfq.isPending?'Creating…':'Create RFQ'}<ArrowUpRightIcon size={14}/></button>{createRfq.error?<div className="mt-3"><ErrorNotice message={createRfq.error.message}/></div>:null}</section>
      <section className="pf-panel p-5"><div className="pf-section-head"><div><div className="pf-card-title">2. Invite suppliers</div><div className="pf-card-subtitle">A quote cannot be recorded unless its supplier was invited.</div></div><span className="pf-step-dot"><BuildingIcon size={13}/></span></div><select className="pf-input mt-5" value={inviteRfqId} onChange={e=>{setInviteRfqId(e.target.value);setSelectedVendorIds([])}}><option value="">Open RFQ</option>{openOptions.map((r:any)=><option key={r.id} value={r.id}>{r.number} · {r.title}</option>)}</select><div className="mt-3 max-h-[180px] space-y-1 overflow-auto">{!vendors.data?.length?<EmptyNotice>No active suppliers have been created.</EmptyNotice>:vendors.data.map((v:any)=><label key={v.id} className="flex cursor-pointer items-center gap-2 rounded-[9px] border border-slate-200 px-3 py-2 hover:bg-slate-50"><input type="checkbox" disabled={!inviteRfqId} checked={selectedVendorIds.includes(v.id)} onChange={()=>toggleVendor(v.id)}/><span className="text-[10.5px] font-semibold">{v.displayName}</span></label>)}</div><button disabled={!inviteRfqId||!selectedVendorIds.length||invite.isPending} className="pf-btn pf-btn-primary mt-3 w-full" onClick={()=>invite.mutate()}>{invite.isPending?'Inviting…':'Invite selected suppliers'}</button>{invite.error?<div className="mt-3"><ErrorNotice message={invite.error.message}/></div>:null}</section>
      <section className="pf-panel p-5"><div className="pf-section-head"><div><div className="pf-card-title">3. Record quote</div><div className="pf-card-subtitle">Capture the commercial facts used in comparison.</div></div><span className="pf-step-dot"><RepeatIcon size={13}/></span></div><select className="pf-input mt-5" value={rfqId} onChange={e=>{setRfqId(e.target.value);setVendorId('');const r=rows.find((x:any)=>x.id===e.target.value);setQuoteItems(r?.items??[]);setPrices({});}}><option value="">Open RFQ</option>{openOptions.map((r:any)=><option key={r.id} value={r.id}>{r.number} · {r.title}</option>)}</select><select className="pf-input mt-3" value={vendorId} onChange={e=>setVendorId(e.target.value)}><option value="">Invited supplier</option>{invited.map((i:any)=><option key={i.vendorId} value={i.vendorId}>{i.vendor.displayName}</option>)}</select>{quoteItems.length?<><div className="mt-4 space-y-2">{quoteItems.map((i:any)=><div key={i.id} className="grid gap-2 md:grid-cols-[1fr_100px_130px]"><div className="rounded-[9px] border border-slate-200 bg-slate-50 px-3 py-2 text-[10.5px] font-semibold">{i.description}<div className="mt-1 text-[9px] font-normal text-slate-400">{Number(i.quantity)} {i.unit}</div></div><input className="pf-input" value={Number(i.quantity)} readOnly/><input className="pf-input" type="number" min="0" step="1" placeholder="Unit price" value={prices[i.id]??''} onChange={e=>setPrices({...prices,[i.id]:e.target.value})}/></div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><input className="pf-input" value={referenceNumber} onChange={e=>setReferenceNumber(e.target.value)} placeholder="Supplier quote reference"/><input className="pf-input" type="date" min={new Date().toISOString().slice(0,10)} value={validUntil} onChange={e=>setValidUntil(e.target.value)}/><input className="pf-input" type="number" min="0" value={leadTime} onChange={e=>setLeadTime(e.target.value)} placeholder="Lead time (days)"/><input className="pf-input" value={payment} onChange={e=>setPayment(e.target.value)} placeholder="Payment terms"/></div><button disabled={!rfqId||!vendorId||quoteItems.some((i:any)=>!prices[i.id]||Number(prices[i.id])<0)||createQuote.isPending} className="pf-btn pf-btn-primary mt-3 w-full" onClick={()=>createQuote.mutate()}>{createQuote.isPending?'Recording…':'Record quotation'}</button></>:<div className="mt-5 rounded-[10px] border border-dashed border-slate-200 p-4 text-[10px] text-slate-500">Choose an open RFQ and an invited supplier to load its line items.</div>}{createQuote.error?<div className="mt-3"><ErrorNotice message={createQuote.error.message}/></div>:null}</section>
    </div>
    <section className="mt-5 space-y-4">{!rows.length?<EmptyNotice>No sourcing events yet.</EmptyNotice>:rows.map((r:any)=><div key={r.id} className="pf-panel overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-100 p-5"><div><div className="flex items-center gap-2"><span className="pf-label">{r.number}</span><StatusBadge value={r.status}/></div><h2 className="mt-2 text-[16px] font-bold tracking-[-.02em]">{r.title}</h2><p className="mt-1 text-[10px] text-slate-500">Source request: {r.purchaseRequest?.title ?? '—'} · deadline {formatDate(r.responseDeadline)}</p></div>{r.selectedQuoteId?<Link href="/orders" className="pf-btn pf-btn-primary">Continue to purchase order <ArrowUpRightIcon size={14}/></Link>:null}</div><div className="grid gap-5 p-5 lg:grid-cols-[.8fr_1.2fr]"><div><div className="pf-label">Invitations</div><div className="mt-3 space-y-2">{r.invitations?.length?r.invitations.map((i:any)=><div key={i.id} className="flex items-center justify-between gap-3 rounded-[9px] border border-slate-200 p-3"><div className="text-[10.5px] font-semibold">{i.vendor.displayName}</div><StatusBadge value={i.status}/></div>):<div className="text-[10px] text-slate-500">No suppliers invited.</div>}</div></div><div><div className="pf-label">Commercial comparison</div>{r.quotes?.length?<div className="mt-3 overflow-x-auto"><Table><thead><tr><Th>Supplier</Th><Th>Total</Th><Th>Lead</Th><Th>Terms</Th><Th>Valid until</Th><Th>Decision</Th></tr></thead><tbody>{r.quotes.map((q:any)=><tr key={q.id}><Td><div className="font-semibold text-slate-800">{q.vendor.displayName}</div><div className="mt-1 text-[9px] text-slate-400">{q.referenceNumber}</div></Td><Td className="font-semibold">{formatCurrency(q.totalCents)}</Td><Td>{q.leadTimeDays??'—'} days</Td><Td>{q.paymentTerms??'—'}</Td><Td>{formatDate(q.validUntil)}</Td><Td>{q.status==='SUBMITTED'&&r.status==='OPEN'?<button className="pf-btn pf-btn-primary" disabled={select.isPending} onClick={()=>select.mutate({rfqId:r.id,quoteId:q.id})}><CheckIcon size={13}/>Select</button>:<StatusBadge value={q.status}/>}</Td></tr>)}</tbody></Table></div>:<div className="mt-3 rounded-[10px] border border-dashed border-slate-200 p-5 text-[10px] text-slate-500">No quotations recorded for this event.</div>}</div></div></div>)}{select.error?<ErrorNotice message={select.error.message}/>:null}</section>
  </div>;
}
